### ISSUE TITLE
Configure UN Layers: Rules Layer

### ISSUE THREAD

**Issue by vertigork** [Esri/Utility-Data-Management-Support-Tools#5]
**Is your feature request related to a problem? Please describe.**
The tool currently requires that the rules layer be in the map.  This can lead to problems if a user removes the layers, points the layer to the wrong database, or if a user does not know how to add the layer to the map.  In some cases adding the rule table to the map is a complicated multi-step process (like with file geodatabases).

**Describe the solution you'd like**
Instead of warning the user to add a rules layer to the map it would be nice if the arcade expression handled this via the $datastore profile.  This information can be derived when the expression is generated (similar to the Add UN System Tables tool) and embedded in the arcade expression (e.g. $datastore, UN_5_Rules for a FGDB).

**Describe alternatives you've considered**
This is related to other bugs with the UDMS tools where the Add UN System Tables tool doesn't always add the tables to the map and even when it does the tables must be renamed in order for this tool to use them.

**Additional context**
This was tested against the File Geodatabase and Network Editor map from the Esri Electric Foundation solution.

**Comment by pLeBlanc93** [comment]
Interesting, I assumed that `$datastore` was not supported in the popup profile. Looks like it has been there for 3 years now...
https://developers.arcgis.com/arcade/guide/release-notes/#featureset-support-in-popups-and-attribute-rules

The rules layer *was* supposed to be automatically added by the tool, but for some reason it doesn't always work. Hence the warning. Moot point though, because I'm not seeing a reason to use `$map` anymore...

**Comment by MikeMillerGIS** [comment]
@vertigork can you verify?

**Comment by vertigork** [comment]
i'll test this out ASAP

**Comment by vertigork** [comment]
@MikeMillerGIS  tested in ArcGIS Pro against an active project, active map, with subtype group layers.
